# Generated by Django 2.2 on 2021-06-18 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_printer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='image',
            field=models.ImageField(default=1, upload_to='logos/computer'),
            preserve_default=False,
        ),
    ]
