# Generated by Django 2.2 on 2021-06-13 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pdState',
            field=models.BooleanField(default=True, verbose_name='visto / oculto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='odItem',
            field=models.ManyToManyField(to='core.OrderItem', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='odUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordenado / Ordenar'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_calle',
            field=models.CharField(max_length=256, verbose_name='Calle'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_data',
            field=models.TextField(verbose_name='Dato'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_number',
            field=models.CharField(max_length=256, verbose_name='Numero'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_phone',
            field=models.CharField(max_length=10, verbose_name='Telefono'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oiAmount',
            field=models.IntegerField(default=1, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oiItem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Products', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='oiUser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='ordered',
            field=models.BooleanField(default=False, verbose_name='Ordenado / Ordenar'),
        ),
    ]
