# Generated by Django 2.2 on 2021-06-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pdName',
            field=models.CharField(max_length=60, verbose_name='Nombre del pruducto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdState',
            field=models.BooleanField(default=True, verbose_name='Estado = Visto/Oculto'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdUser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
