# Generated by Django 2.2 on 2021-06-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210613_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brands',
            name='brCreate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='brands',
            name='brUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cgCreate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='cgUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdCreate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='pdUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slCreate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='slUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
