# Generated by Django 2.2 on 2021-06-16 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210615_2257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pdUser',
        ),
    ]
